apiVersion: v1
kind: Service
metadata:
  name: seed-microservice-kotlin
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name : http
  selector:
    app: seed-microservice-kotlin
  type: LoadBalancer
